version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: Döner#22
      POSTGRES_DB: n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /home/regie/schulolympiade/dashboard/data:/results
      - /home/regie/schulolympiade/dashboard/public/data:/emojis
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      WEBHOOK_TUNNEL_URL: http://192.168.100.73:5678
      N8N_HOST: 192.168.100.73
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: Döner#22
      DB_POSTGRESDB_SCHEMA: public
      GENERIC_TIMEZONE: Europe/Berlin
      TZ: Europe/Berlin
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: admin
      N8N_BASIC_AUTH_PASSWORD: Döner#22
      N8N_SECURE_COOKIE: false
    volumes:
      - n8n_data:/home/node/.n8n
      - /home/regie/schulolympiade/dashboard/data:/results
      - /home/regie/schulolympiade/dashboard/public/data:/emojis
    depends_on:
      - postgres

volumes:
  postgres_data:
  n8n_data:
