version: "3"

services:
  nginx:
    image: nginx:stable
    container_name: nginx-redirect
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
